CREATE DATABASE IF NOT EXISTS world
  CHARACTER SET utf8mb4;

USE world;

DROP TABLE IF EXISTS countries;
CREATE TABLE IF NOT EXISTS countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL);